# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tyrantmanager}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Hinegardner"]
  s.date = %q{2009-08-22}
  s.default_executable = %q{tyrantmanager}
  s.description = %q{A command line tool for managing Tokyo Tyrant instances.  It allows for the
creation, starting, stopping, listing, stating of many tokyo tyrant instances
all on the same machine.  The commands can be applied to a single or multiple
instances.}
  s.email = %q{jeremy@copiousfreetime.org}
  s.executables = ["tyrantmanager"]
  s.extra_rdoc_files = [
    "HISTORY.rdoc",
     "LICENSE",
     "README.rdoc",
     "lib/tyrant_manager.rb",
     "lib/tyrant_manager/cli.rb",
     "lib/tyrant_manager/command.rb",
     "lib/tyrant_manager/commands/create_instance.rb",
     "lib/tyrant_manager/commands/list.rb",
     "lib/tyrant_manager/commands/replication_status.rb",
     "lib/tyrant_manager/commands/start.rb",
     "lib/tyrant_manager/commands/stats.rb",
     "lib/tyrant_manager/commands/status.rb",
     "lib/tyrant_manager/commands/stop.rb",
     "lib/tyrant_manager/log.rb",
     "lib/tyrant_manager/paths.rb",
     "lib/tyrant_manager/runner.rb",
     "lib/tyrant_manager/tyrant_instance.rb",
     "lib/tyrant_manager/version.rb",
     "lib/tyrantmanager.rb"
  ]
  s.files = [
    "HISTORY.rdoc",
     "LICENSE",
     "README.rdoc",
     "bin/tyrantmanager",
     "data/config.rb",
     "data/default_instance_config.rb",
     "gemspec.rb",
     "lib/tyrant_manager.rb",
     "lib/tyrant_manager.rb",
     "lib/tyrant_manager/cli.rb",
     "lib/tyrant_manager/cli.rb",
     "lib/tyrant_manager/command.rb",
     "lib/tyrant_manager/command.rb",
     "lib/tyrant_manager/commands/create_instance.rb",
     "lib/tyrant_manager/commands/create_instance.rb",
     "lib/tyrant_manager/commands/list.rb",
     "lib/tyrant_manager/commands/list.rb",
     "lib/tyrant_manager/commands/replication_status.rb",
     "lib/tyrant_manager/commands/replication_status.rb",
     "lib/tyrant_manager/commands/start.rb",
     "lib/tyrant_manager/commands/start.rb",
     "lib/tyrant_manager/commands/stats.rb",
     "lib/tyrant_manager/commands/stats.rb",
     "lib/tyrant_manager/commands/status.rb",
     "lib/tyrant_manager/commands/status.rb",
     "lib/tyrant_manager/commands/stop.rb",
     "lib/tyrant_manager/commands/stop.rb",
     "lib/tyrant_manager/log.rb",
     "lib/tyrant_manager/log.rb",
     "lib/tyrant_manager/paths.rb",
     "lib/tyrant_manager/paths.rb",
     "lib/tyrant_manager/runner.rb",
     "lib/tyrant_manager/runner.rb",
     "lib/tyrant_manager/tyrant_instance.rb",
     "lib/tyrant_manager/tyrant_instance.rb",
     "lib/tyrant_manager/version.rb",
     "lib/tyrant_manager/version.rb",
     "lib/tyrantmanager.rb",
     "lib/tyrantmanager.rb",
     "spec/command_spec.rb",
     "spec/paths_spec.rb",
     "spec/spec_helper.rb",
     "spec/tyrant_instance_spec.rb",
     "spec/tyrant_manager_spec.rb",
     "spec/version_spec.rb",
     "tasks/announce.rake",
     "tasks/config.rb",
     "tasks/distribution.rake",
     "tasks/documentation.rake",
     "tasks/rspec.rake",
     "tasks/rubyforge.rake",
     "tasks/utils.rb"
  ]
  s.homepage = %q{http://copiousfreetime.rubyforge.org/tyrantmanager/}
  s.rdoc_options = ["--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{copiousfreetime}
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{A command line tool for managing Tokyo Tyrant instances}
  s.test_files = [
    "spec/paths_spec.rb",
     "spec/tyrant_instance_spec.rb",
     "spec/tyrant_manager_spec.rb",
     "spec/spec_helper.rb",
     "spec/command_spec.rb",
     "spec/version_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<loquacious>, ["~> 1.3.0"])
      s.add_runtime_dependency(%q<rufus-tokyo>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<logging>, ["~> 1.1.4"])
      s.add_runtime_dependency(%q<main>, ["~> 2.8.4"])
      s.add_development_dependency(%q<configuration>, [">= 0.0.5"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.3"])
    else
      s.add_dependency(%q<loquacious>, ["~> 1.3.0"])
      s.add_dependency(%q<rufus-tokyo>, ["~> 1.0.0"])
      s.add_dependency(%q<logging>, ["~> 1.1.4"])
      s.add_dependency(%q<main>, ["~> 2.8.4"])
      s.add_dependency(%q<configuration>, [">= 0.0.5"])
      s.add_dependency(%q<rake>, ["~> 0.8.3"])
    end
  else
    s.add_dependency(%q<loquacious>, ["~> 1.3.0"])
    s.add_dependency(%q<rufus-tokyo>, ["~> 1.0.0"])
    s.add_dependency(%q<logging>, ["~> 1.1.4"])
    s.add_dependency(%q<main>, ["~> 2.8.4"])
    s.add_dependency(%q<configuration>, [">= 0.0.5"])
    s.add_dependency(%q<rake>, ["~> 0.8.3"])
  end
end
